// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ny6sMR2xOMNVZ2UPweDB19B9_kdMbWY',
    appId: '1:91681130800:web:ee26c46815850c0c27a0f5',
    messagingSenderId: '91681130800',
    projectId: 'smart-security-coeai',
    authDomain: 'smart-security-coeai.firebaseapp.com',
    storageBucket: 'smart-security-coeai.appspot.com',
    measurementId: 'G-QM36XQEYTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1YLy6MuIbhNkuubTr4bEQB3GyUCuXRBE',
    appId: '1:91681130800:android:ac6746243553cca427a0f5',
    messagingSenderId: '91681130800',
    projectId: 'smart-security-coeai',
    storageBucket: 'smart-security-coeai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jbWrCaaBrywH5YV0_TJQCqUgwNsXN8w',
    appId: '1:91681130800:ios:3487f8e55a59f93627a0f5',
    messagingSenderId: '91681130800',
    projectId: 'smart-security-coeai',
    storageBucket: 'smart-security-coeai.appspot.com',
    iosBundleId: 'com.example.smartCommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jbWrCaaBrywH5YV0_TJQCqUgwNsXN8w',
    appId: '1:91681130800:ios:3487f8e55a59f93627a0f5',
    messagingSenderId: '91681130800',
    projectId: 'smart-security-coeai',
    storageBucket: 'smart-security-coeai.appspot.com',
    iosBundleId: 'com.example.smartCommute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ny6sMR2xOMNVZ2UPweDB19B9_kdMbWY',
    appId: '1:91681130800:web:fe284ccdf0b927c027a0f5',
    messagingSenderId: '91681130800',
    projectId: 'smart-security-coeai',
    authDomain: 'smart-security-coeai.firebaseapp.com',
    storageBucket: 'smart-security-coeai.appspot.com',
    measurementId: 'G-L0NJH4YFEV',
  );
}
